name: SIMPLE-DEPLOY Weather

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: rozkalnsandris/ops-workflows/.github/workflows/simple-deploy.yml@297f554519849ab8dcaadc5517e60b8269a6efaa # v1.0.0
    with:
      source_sha: ${{ github.sha }}
